version: "3.3"
services:
  miracum-mapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miracum-mapper
    ports:
      - "8080:8080"
    environment:
      - MIRACUM_MAPPER_KEYCLOAK_ENDPOINT=http://keycloak:8080/auth
      - MIRACUM_MAPPER_KEYCLOAK_REALM=mapper
      - MIRACUM_MAPPER_KEYCLOAK_CLIENT_ID=mapper
      - MIRACUM_MAPPER_KEYCLOAK_CLIENT_SECRET=secret
      - MIRACUM_MAPPER_SKIP_SSL_CHECK=true
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    # healthcheck:
    #   test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - miracum-pgdata:/var/lib/postgresql/data
    hostname: postgres
