version: "3.3"
services:
  miracum-postgres:
    image: postgres:16
    container_name: miracum-postgres
    hostname: miracum-postgres
    environment:
      POSTGRES_DB: miracum_db
      POSTGRES_USER: miracum_user
      POSTGRES_PASSWORD: miracum_password
    ports:
      - "5432:5432"
    volumes:
      - miracum_postgres_data:/var/lib/postgresql/data
    networks:
      - miracum_public_network
      - miracum_network_internal

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-postgres
    networks:
      - miracum_public_network
      - keycloak_network_internal

  keycloak-postgres:
    image: postgres:16
    container_name: keycloak-postgres
    hostname: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network_internal

volumes:
  miracum_postgres_data:
    name: miracum_postgres_data
  keycloak_postgres_data:
    name: keycloak_postgres_data

networks:
  miracum_public_network:
    driver: bridge
  miracum_network_internal:
    driver: bridge
    internal: true
  keycloak_network_internal:
    driver: bridge
    internal: true
