# config.yml
version: 1.0.0
database:
    retry: 30
    sleep: 5
    # migration:
    #   enabled: false
# rate_limit:
#   enabled: true
#   limit: 100
#   burst: 10
cors:
    allowed_origins:
        - "*"